# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 14:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('section', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('level', models.IntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')])),
                ('question_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reference', models.URLField(blank=True, max_length=255)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey')),
            ],
            options={
                'ordering': ('section', 'level', 'question_number'),
            },
        ),
    ]
