# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
