# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 14:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_de_unique_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')], null=True),
        ),
    ]
