# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_more_precise_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.Survey'),
        ),
    ]
