# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_surveyquestion_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='section_code',
            field=models.CharField(default='4.1', max_length=255),
            preserve_default=False,
        ),
    ]
