# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_surveyquestion_section_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='upload_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
