# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_surveyresponse_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
    ]
