# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_level_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='submitted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
