# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_rename_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
