# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_verbose-names'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='upload_type',
            field=models.CharField(blank=True, choices=[('policy', 'Policy'), ('procedure', 'Procedure'), ('process', 'Process')], max_length=255),
        ),
    ]
