# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 08:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_add_survey_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SurveySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_area', to='surveys.SurveyArea')),
            ],
            options={
                'ordering': ['area', 'number'],
            },
        ),
    ]
