# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 15:14
from __future__ import unicode_literals

from django.db import migrations

SURVEY_AREA = [{
	"name" : "Financial management",
	"number" : 5
},{
	"name" : "Human resources",
	"number" : 6
},{
	"name" : "Procurement",
	"number" : 7
},{
	"name" : "Governance",
	"number" : 8
}]

SURVEY_SECTION = [{
	"area" : "Financial management",
	"sections" : [{
		"name" : "Financial management",
		"number" : 1
	},{
		"name" : "Income management",
		"number" : 2
	},{
		"name" : "Expenditure management",
		"number" : 3
	},{
		"name" : "Property, plant and equipment",
		"number" : 4
	},{
		"name" : "Cash, bank and treasury management",
		"number" : 5
	},{
		"name" : "Inventory management",
		"number" : 6
	},{
		"name" : "Travel and expenses",
		"number" : 7
	},{
		"name" : "Sub-grantee management",
		"number" : 8
	},{
		"name" : "Financial management systems",
		"number" : 9
	},{
		"name" : "Financial reporting",
		"number" : 10
	}]
},{
	"area" : "Human resources",
	"sections" : [{
		"name" : "Human resource management and payroll",
		"number" : 1
	},{
		"name" : "Staff development",
		"number" : 2
	}]
},{
	"area" : "Procurement",
	"sections" : [{
		"name" : "Planning",
		"number" : 1
	},{
		"name" : "Contract management",
		"number" : 2
	}]
},{
	"area" : "Governance",
	"sections" : [{
		"name" : "General",
		"number" : 1
	},{
		"name" : "Grant management and compliance",
		"number" : 2
	},{
		"name" : "Audit",
		"number" : 3
	},{
		"name" : "Risk management",
		"number" : 4
	}]
}]

def save_survey_section(apps, area, name, number):
	SurveySection = apps.get_model('surveys', 'SurveySection')
	survey_section = SurveySection(area=area, name=name, number=number)
	survey_section.save()

def save_survey_area(apps, name, number):
	SurveyArea = apps.get_model('surveys', 'SurveyArea')
	survey_area = SurveyArea(name=name, number=number)
	survey_area.save()

def add_survey_area_section(apps, schema_editor):
	SurveyArea = apps.get_model('surveys', 'SurveyArea')
	
	for area in SURVEY_AREA:
		save_survey_area(apps, area['name'], area['number'])

	for section in SURVEY_SECTION:
		survey_area = SurveyArea.objects.get(name=section['area'])
		for section_item in section['sections']:
			save_survey_section(apps, survey_area,section_item['name'],section_item['number'])


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_add_area_section'),
    ]

    operations = [
    	migrations.RunPython(add_survey_area_section),
    ]
