# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_initial_area_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='section',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='section',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='surveys.SurveySection'),
        ),
    ]
