# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 11:04
from __future__ import unicode_literals

from django.db import migrations


def set_sections(apps, schema_editor):
    SurveyQuestion = apps.get_model('surveys', 'SurveyQuestion')
    SurveySection = apps.get_model('surveys', 'SurveySection')
    SurveyArea = apps.get_model('surveys', 'SurveyArea')

    areas = SurveyArea.objects.all()
    sections = SurveySection.objects.select_related('area')

    area_lookup = { area.number: area for area in areas }
    section_lookup = {
        '{}.{}'.format(section.area.number, section.number): section
        for section in sections
    }

    for question in SurveyQuestion.objects.all():
        section_code = question.section_code
        area_number, section_number = section_code.split('.')
        area_number = int(area_number)
        section_number = int(section_number)

        try:
            area = area_lookup[area_number]
        except KeyError:
            area_name = '{} (legacy area)'.format(area_number)
            area = SurveyArea.objects.create(number=area_number, name=area_name)
            area_lookup[area_number] = area

        try:
            section = section_lookup[section_code]
        except KeyError:
            section_name = '{} (legacy section)'.format(section_code)
            section = SurveySection.objects.create(area=area, number=section_number, name=section_name)
            section_lookup[section_code] = section

        question.section = section
        question.save()

class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_questions_foreignkey_section'),
    ]

    operations = [
        migrations.RunPython(set_sections),
    ]
