# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_set_question_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='section_code',
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='surveys.SurveySection'),
        ),
    ]
