# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_removed_section_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=233)),
                ('document', models.FileField(max_length=255, null=True, upload_to='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.SurveyQuestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyResponse')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='surveyanswer',
            unique_together=set([('response', 'question')]),
        ),
    ]
