# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0025_rename_response_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='value',
            field=models.CharField(choices=[('yes', 'Yes'), ('in-progress', 'In progress'), ('no', 'No'), ('not-applicable', 'Not Applicable')], max_length=233),
        ),
    ]
