# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models


def set_organisation(apps, schema_editor):
    SurveyResponse = apps.get_model('surveys', 'SurveyResponse')

    responses = SurveyResponse.objects.filter(
        organisation__isnull=True,
    ).select_related(
        'user__organisation',
    )
    for response in SurveyResponse.objects.all():
        response.organisation = response.user.organisation
        response.save()


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_add_survey_response_organisation'),
        ('users', '0027_user_organisation_required'),
    ]

    operations = [
        migrations.RunPython(set_organisation, migrations.RunPython.noop),
    ]
