# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0028_set_response_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='user',
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.Organisation'),
        ),
    ]
