# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0029_remove_response_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='invited_by',
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')], verbose_name='target tier'),
        ),
    ]
