# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_remove_survey_response_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.Survey'),
        ),
    ]
