# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 12:36
from __future__ import unicode_literals

from django.db import migrations
from django.utils.html import linebreaks


def make_name_html(apps, schema_editor):
    SurveyQuestion = apps.get_model('surveys', 'SurveyQuestion')

    for question in SurveyQuestion.objects.all():
        question.name = linebreaks(question.name)
        question.save()


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0031_alter_surveyresponse_survey_field'),
    ]

    operations = [
        migrations.RunPython(make_name_html, migrations.RunPython.noop),
    ]
