# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0034_remove_redundant_m2m_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='invalid',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='score',
        ),
    ]
