# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_attach_project'),
        ('surveys', '0035_remove_score_and_invalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswerDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyAnswer')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Document')),
            ],
        ),
    ]
