# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 07:14
from __future__ import unicode_literals

from django.db import migrations


def copy_documents(OldDocument, NewDocument):
    for old in OldDocument.objects.all():
        NewDocument.objects.create(
            answer=old.answer,
            document=old.document,
            explanation=old.explanation,
            created=old.created,
        )


def copy_forwards(apps, schema_editor):
    QuestionDocument = apps.get_model('documents', 'QuestionDocument')
    SurveyAnswerDocument = apps.get_model('surveys', 'SurveyAnswerDocument')
    copy_documents(QuestionDocument, SurveyAnswerDocument)


def copy_backwards(apps, schema_editor):
    QuestionDocument = apps.get_model('documents', 'QuestionDocument')
    SurveyAnswerDocument = apps.get_model('surveys', 'SurveyAnswerDocument')
    copy_documents(SurveyAnswerDocument, QuestionDocument)


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0036_add_answer_document'),
    ]

    operations = [
        migrations.RunPython(copy_forwards, copy_backwards),
    ]
