# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0039_copy_answer_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswer',
            name='document',
        ),
    ]
