# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0040_remove_answer_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswer',
            name='value',
            field=models.CharField(choices=[('yes', 'Yes'), ('in-progress', 'In progress'), ('no', 'No')], max_length=233),
        ),
    ]
