# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 20:13
from __future__ import unicode_literals

from django.db import migrations


def copy_na_to_no(apps, schema_editor):
    SurveyAnswer = apps.get_model('surveys', 'SurveyAnswer')
    SurveyAnswer.objects.filter(value='not-applicable').update(value='no')


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0041_remove_response_value_na'),
    ]

    operations = [
        migrations.RunPython(copy_na_to_no, migrations.RunPython.noop),
    ]
