# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0043_invite_last_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
