# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0044_survey_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswer',
            name='value',
            field=models.CharField(choices=[('yes', 'Yes'), ('in-progress', 'In progress'), ('no', 'No'), ('not-applicable', 'Not Applicable')], max_length=233),
        ),
    ]
