# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180221_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
