# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180221_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('grantee', 'Grantee'), ('grantor', 'Grantor')], default='grantor', max_length=255),
        ),
    ]
