# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact',
            new_name='organisation_contact',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mobile',
            new_name='user_mobile',
        ),
    ]
