# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180222_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address2',
            new_name='address_2',
        ),
    ]
