# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
    ]
