# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 13:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_changed_website_to_url_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
