# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 07:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_changed_website_to_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organisation_contact',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Contact number must be entered in the format: '+919999999'.        Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_mobile',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Contact number must be entered in the format: '+919999999'.        Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
