# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 11:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_verify_email_mixin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(default='', max_length=100)),
                ('department_name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=300)),
                ('address_1', models.CharField(default='', max_length=255)),
                ('address_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(default='', max_length=100)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('zip', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('organisation_contact', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Contact number must be entered in the format: '+919999999'.        Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('website', models.URLField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation_contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zip',
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Organisation'),
        ),
    ]
