# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_seperate_organization_user_model'),
        ('users', '0018_auto_20180304_1319'),
    ]

    operations = [
    ]
