# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_organisation_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
