# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_added_new_organisation_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='department_name',
            new_name='known_as',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='organisation_name',
            new_name='legal_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='job_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='biography',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='type',
            field=models.CharField(choices=[('non_government', 'Non Governmental'), ('international_non_governmental', 'International Non Governmental'), ('governmental', 'Governmental'), ('community_based', 'Community Based'), ('community_societal', 'Community Societal'), ('research_or_technology', 'Research / Technology'), ('charitable', 'Charitable'), ('foundation', 'Foundation'), ('other', 'Other')], max_length=255),
        ),
    ]
