# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 09:43
from __future__ import unicode_literals

from django.db import migrations

def set_organisation(apps, schema_editor):
    Organisation = apps.get_model('users', 'Organisation')
    User = apps.get_model('users', 'User')

    users = User.objects.filter(organisation__isnull=True)
    if not users:
        return

    for user in users:
        organisation, _created = Organisation.objects.get_or_create(
            legal_name=user.name,
            defaults={'type': 'other'},
        )
        user.organisation = organisation
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_updated_organisation_fields'),
    ]

    operations = [
        migrations.RunPython(set_organisation, migrations.RunPython.noop),
    ]
