# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_removed_section_code'),
        ('users', '0025_updated_organisation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grantee', to='users.Organisation')),
                ('grantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grantor', to='users.Organisation')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey')),
            ],
        ),
    ]
