# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_organisation_required'),
        ('users', '0027_add_invitation_level_status'),
    ]

    operations = [
    ]
