# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 13:03
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def make_admins(apps, schema_editor):
    """Ensure each Organisation has a user with the admin role."""
    call_command('sync_roles')
    Group = apps.get_model('auth', 'Group')
    Organisation = apps.get_model('users', 'Organisation')

    admin = Group.objects.get(name='admin')

    organisations = Organisation.objects.prefetch_related('user_set')
    organisations = organisations.exclude(user__groups__name='admin')
    for organisation in organisations:
        try:
            user = organisation.user_set.all()[0]
        except IndexError:
            pass
        else:
            user.groups.add(admin)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_merge_20180321_1655'),
    ]

    operations = [
        migrations.RunPython(make_admins, migrations.RunPython.noop),
    ]
