# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_merge_20180321_1655'),
        ('users', '0028_invitation_model_for_unregistered_user'),
    ]

    operations = [
    ]
