# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_make_organisation_admins'),
        ('users', '0029_merge_20180322_1133'),
    ]

    operations = [
    ]
