# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_added_grantee_email_field_for_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='type',
            field=models.CharField(choices=[('academic_training_and_research', 'Academic, Training and Research'), ('charitable', 'Charitable'), ('community_based', 'Community Based'), ('community_societal', 'Community Societal'), ('foundation', 'Foundation'), ('government', 'Government'), ('international_ngo', 'International NGO'), ('multilateral', 'Multilateral'), ('national_ngo', 'National NGO'), ('other_public_sector', 'Other Public Sector'), ('private_sector', 'Private Sector'), ('public_private_partnership', 'Public Private Partnership'), ('regional_ngo', 'Regional NGO'), ('other', 'Other')], max_length=255),
        ),
    ]
