# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-27 11:58
from __future__ import unicode_literals

from django.db import migrations

def set_last_sent(apps, schema_editor):
    Invitation = apps.get_model('users', 'Invitation')
    all_invites = Invitation.objects.all()

    for invite in all_invites:
        invite.last_sent = invite.created
        invite.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_invite_last_sent'),
    ]

    operations = [
        migrations.RunPython(set_last_sent),
    ]
