# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_migrate_invite_last_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
