# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_update_organisation_fields'),
    ]

    operations = [
    ]
