# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_add_default_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='country',
        ),
    ]
