# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_load_default_countries'),
        ('users', '0038_remove_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='countries.Country'),
        ),
    ]
