# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 14:32
from __future__ import unicode_literals

from django.db import migrations


def default_types(apps, schema_editor):
    OrganisationType = apps.get_model('users', 'OrganisationType')
    names = (
        'Academic',
        'Charitable/Foundation',
        'Charitable/other',
        'Community Based',
        'Community Societal',
        'Foundation',
        'Government',
        'Independent',
        'International NGO',
        'National NGO',
        'Non Government',
        'Not for profit',
        'Other Public Sector',
        'Paristatol',
        'Private Sector',
        'Public Sector',
        'Private Partnership',
        'Regional NGO',
        'Research',
        'State owned enterprises',
        'Training Trust',
        'Universities',
        'Other',
    )

    OrganisationType.objects.bulk_create([
        OrganisationType(name=name, sort_order=sort_order + 1)
        for sort_order, name in enumerate(names)
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_add_organisation_types'),
    ]

    operations = [
        migrations.RunPython(default_types, migrations.RunPython.noop),
    ]
