# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_add_default_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ('-last_sent',)},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ('legal_name',)},
        ),
        migrations.AddField(
            model_name='invitation',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
