# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_invite_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='privacy_acceptance_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organisation',
            name='terms_acceptance_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
