# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_invite_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
