# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_organisation_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
