# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_add_terms_privacy_dates'),
        ('subscriptions', '0001_assessment_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_included', models.IntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New/Awaiting payment'), ('in-progress', 'In Progress'), ('approved', 'Approved/Payed'), ('canceled', 'Canceled/Rejected')], default='new', max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='subscriptions.Order')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentpurchase',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_purchase', to='subscriptions.Order'),
        ),
        migrations.AddField(
            model_name='assessmentpurchase',
            name='package',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='subscriptions.AssessmentPackage'),
        ),
    ]
