# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-28 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_package_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentpurchase',
            name='number_included',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assessmentpurchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
