# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_assessment_purchase_null_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentpurchase',
            name='number_included',
            field=models.IntegerField(null=True),
        ),
    ]
