# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 17:55
from __future__ import unicode_literals

from dateutil.relativedelta import relativedelta

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_number_included_not_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('approved', 'Paid'), ('canceled', 'Canceled')], default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=lambda: timezone.now() + relativedelta(years=1)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=9),
        ),
    ]
