# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-14 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_subscription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentpurchase',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
