# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_added_document_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
