# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_added_expiry_field_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
