# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0032_question_name_richtext'),
        ('documents', '0003_made_expiry_field_not_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.SurveyAnswer')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.Document')),
            ],
        ),
    ]
