# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_answer_document_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondocument',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='surveys.SurveyAnswer'),
        ),
        migrations.AlterField(
            model_name='questiondocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='documents.Document'),
        ),
    ]
