# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_question_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
