# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 14:00
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def default_countries(apps, schema_editor):
    call_command('loaddata', 'default_countries')


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(default_countries),
    ]
